name: Accessibility Validation

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '6.0.x'
                include-prerelease: true
              
            - name: Docker commands
              run: docker-compose build
            - run: docker-compose up -d
            
            - name: Scan for accessibility issues
              uses: microsoft/accessibility-insights-action@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  url: http://localhost:5106/
                  
            - name: Upload report artifact
              uses: actions/upload-artifact@v2
              with:
                  name: accessibility-reports
                  path: ${{ github.workspace }}/_accessibility-reports
